services:
  
  server1:
    container_name: server1
    image: server
    environment:
      - SERVER_ID=1
      - SERVER_PORT=8001
      - SERVERS=8002,8003,8004,8005

  server2:
    container_name: server2
    image: server
    environment:
      - SERVER_ID=2
      - SERVER_PORT=8002
      - SERVERS=8001,8003,8004,8005

  server3:
    container_name: server3
    image: server
    environment:
      - SERVER_ID=3
      - SERVER_PORT=8003
      - SERVERS=8001,8002,8004,8005
 
  server4:
    container_name: server4
    image: server
    environment:
      - SERVER_ID=4
      - SERVER_PORT=8004
      - SERVERS=8001,8002,8003,8005

  server5:
    container_name: server5
    image: server
    environment:
      - SERVER_ID=5
      - SERVER_PORT=8005
      - SERVERS=8001,8002,8003,8004




